# prevent silent use of root access
system "sudo -k"

# install official taps for formula development
tap "homebrew/cask"
tap "homebrew/core"
# install my tap
tap "rattatap/tap"

# cli tools
brew "actionlint"
brew "rattatap/tap/bind-dnstools"; brew "libidn2", link: false
brew "rattatap/tap/curl-completion"
brew "dos2unix"
brew "duti" # for setting mac file handlers
brew "fastfetch"
brew "fd"
brew "fzf"
brew "git-delta"; brew "libgit2"
brew "glow" # markdown
brew "hyperfine"
brew "jq"
brew "less"
brew "neovim"; brew "luv"
brew "ripgrep"
brew "tlrc" # tldr
brew "tmux"
brew "tree"
brew "typos-cli"
brew "unar"
brew "watch"
brew "xh" # http client
brew "zsh-completions"
brew "zstd"

# pgp
brew "pgpdump"
brew "sequoia-sq"
brew "sequoia-chameleon-gnupg"; brew "rattatap/tap/gpg-from-sq"

# sysadmin
brew "awscli"; brew "saml2aws"
brew "cloudflare-cli4"
brew "rattatap/tap/fwknop-client"
brew "opentofu"
brew "sslscan"
brew "terraform"
brew "trivy"

# kubectl
brew "helm"
brew "k9s"
brew "kubecolor"
brew "kubectl-rook-ceph"
brew "kubelogin"
brew "kubernetes-cli"
brew "kubeseal"
brew "tanka"; brew "jsonnet"; brew "jsonnet-bundler"

# homebrew development
brew "bash-completion"

# dev
brew "gh"
brew "glab"
cask "hex-fiend"
cask "iterm2"
cask "ghostty", args: { no_bin: true }
brew "python"
brew "ruby", link: true

unless Hardware::CPU.virtualized?
  brew "mas"

  # text editors
  cask "textmate"

  # desktop env
  cask "1password"; cask "1password-cli"
  cask "betterdisplay"
  cask "discord"
  cask "firefox"
  cask "freecad"
  cask "macdown-3000"
  cask "omnidisksweeper"
  cask "pacifist"
  cask "skim"
  cask "slack"
  cask "swiftbar" # scripts in menubar
  cask "tower", args: { no_bin: true }
  mas "Dato", id: 1470584107
  mas "Deliveries", id: 290986013
  mas "Numbers", id: 409203825
  mas "Pages", id: 409201541
  mas "Wipr", id: 1662217862

  # misc tools
  cask "mactracker"
  brew "ykman" # yubikey

  # vm
  brew "kind"
  brew "podman"; brew "podman-compose"
  cask "utm"

  # annoyances
  cask "notunes"

  # Install these casks manually. They require sudo, which we normally don't
  # want to allow.
  cask "kicad" if Cask::Caskroom.casks.find{|x| x.to_s == "kicad"}
  cask "xquartz" if Cask::Caskroom.casks.find{|x| x.to_s == "xquartz"}
end

# common dependencies
%w[gettext oniguruma openssl@3 pcre2].each{|x| brew x, link: false}
