#!/bin/sh

case "${0##*/}" in
  *complete*)
    # list contexts for completion, limit to 1
    [ $# -lt 2 ] && kubectl config view -o json | \
      jq -r '."current-context" as $cc | .contexts[] | "\(.name)\tswitch context to \(.name)\(if .name == $cc then " CURRENT" else "" end)"'
    # disable filename completion
    printf ":4\n"
    ;;
  *)
    if [ -n "$1" ]; then
      # set context
      kubectl config use-context "$1"
    else
      # list contexts
      kubectl config view -o json | jq -r '."current-context" as $cc | .contexts[] | "\(.name)\(if .name == $cc then " **" else "" end)"' | egrep '(^\*.*)|(.*\*)|$' --color=auto
    fi
    ;;
esac
