#!/bin/sh

if [ -n "$1" ]; then
  # set context
  kubectl config use-context "$1"
else
  # list contexts
  kubectl config view -o json | jq -r '."current-context" as $cc | .contexts[] | "\(.name)\(if .name == $cc then " **" else "" end)"' | egrep '(^\*.*)|(.*\*)|$' --color=auto
fi
