# create temp fakes of zsh builtins so we can source .zshenv w/o errors
alias setopt=:
source ~/.zshenv
unalias setopt

# macOS: stop yelling about bash
[[ $OSTYPE = darwin* && $BASH_VERSION = 3.* ]] \
  && export BASH_SILENCE_DEPRECATION_WARNING=1

# interactive shells only
if [[ $- == *i* ]]; then
  # minimal prompt
  PS1='\u@\h:\w \$ '

  # bash history settings
  HISTCONTROL=ignoreboth
  shopt -s histappend
  HISTFILE=$XDG_STATE_HOME/bash_history
  HISTSIZE=100000
  HISTFILESIZE=100000
  HISTTIMEFORMAT="%e.%-m.%Y %H:%M  "

  ## completion ##
  if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
    # silince useless errors on bash 3
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" 2> /dev/null
  fi
  complete -C tk tk
  complete -C tofu tofu

  ## local path ##
  [[ ":$PATH:" == *:$HOME/.local/bin:* ]] || PATH=~/.local/bin:"$PATH"
  [[ ":$PATH:" == *:$HOME/.config/libexec:* ]] || PATH=~/.config/libexec:"$PATH"

  ## aliases ##
  alias -- -='cd -'
  alias ..='cd ..'
  alias g=git
  alias ls='ls -F --color=auto'
  alias l='ls' la='ls -A' l1='\ls -1' ll='ls -lh' lla='ls -lAh'
  alias wat='type -a'

  ## editor ##
  if type nvim &>/dev/null; then
    export EDITOR=nvim
    alias vi=nvim vim=nvim
  elif type vim &>/dev/null; then
    export EDITOR=vim
  else
    export EDITOR=vi
  fi

  path () {
    local p
    local IFS=:
    for p in $PATH; do
      echo $p
    done
  }
fi
